# Use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

from langchain_ollama import OllamaLLM, ChatOllama
from langchain_community.utilities.sql_database import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent

# Initialize Ollama LLM (make sure Ollama is running locally)
llm = OllamaLLM(
    model="llama3.1:8b",
    temperature=0.5,
    num_predict=256  # equivalent to max tokens
)

# Simple test
print(llm.invoke("What is the capital of Bihar?"))
